# -*- coding: utf-8 -*-
"""Advanced Machine Learning Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXdSdSuO0p8juPUZIBBQD-sZGOr6sc9D

# 1. Importing Required Libraries

In this section, all required Python libraries for preprocessing, feature selection, model training, and evaluation are imported.
"""

!pip install xgboost -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, f_classif

from sklearn.model_selection import (
    StratifiedKFold,
    GridSearchCV,
    cross_val_score
)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve
)

from xgboost import XGBClassifier

"""# 2. Loading the HIGGS Dataset

The HIGGS dataset was downloaded from the UCI Machine Learning Repository. According to the project requirements, only the first 100,000 samples were used.
"""

!wget -nc https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz

df = pd.read_csv(
    "HIGGS.csv.gz",
    header=None,
    nrows=100000
)

print("Dataset shape:", df.shape)

df.head()

X = df.iloc[:, 1:]
y = df.iloc[:, 0]

print("X shape:", X.shape)
print("y shape:", y.shape)

"""# 3. Outlier Analysis (IQR Method)

Outliers were detected using the Interquartile Range (IQR) method. Instead of removing them completely, extreme values were clipped to the threshold values to preserve the dataset size.
"""

outlier_counts = {}

for col in X.columns:
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((X[col] < lower) | (X[col] > upper)).sum()

    outlier_counts[col] = outliers

outlier_df = pd.DataFrame(
    outlier_counts.items(),
    columns=["Feature", "Outlier Count"]
)

outlier_df

X_clean = X.copy()

for col in X_clean.columns:

    Q1 = X_clean[col].quantile(0.25)
    Q3 = X_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    X_clean[col] = X_clean[col].clip(lower, upper)

print("Outlier processing completed!")

"""# 4. Feature Scaling

MinMaxScaler is applied to transform all features into the range [0,1].
"""

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X_clean)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled.head()

print("Minimum value:", X_scaled.min().min())
print("Maximum value:", X_scaled.max().max())

"""# 5. Feature Selection

ANOVA F-score is used to select the top 15 features.
"""

from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(
    score_func=f_classif,
    k=15
)

X_selected = selector.fit_transform(X_scaled, y)

selected_features = X.columns[selector.get_support()]

print("Selected Features:")
print(selected_features)

X_selected = pd.DataFrame(
    X_selected,
    columns=selected_features
)

X_selected.head()

"""# 6. KNN Model

Nested Cross Validation (5 outer folds, 3 inner folds) is performed for KNN.
"""

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

outer_cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

inner_cv = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

knn_params = {
    'n_neighbors': [3, 5, 7, 9, 11]
}

knn_results = []

fold = 1

for train_idx, test_idx in outer_cv.split(X_selected, y):

    print(f"Processing Fold {fold}/5")

    X_train = X_selected.iloc[train_idx]
    X_test = X_selected.iloc[test_idx]

    y_train = y.iloc[train_idx]
    y_test = y.iloc[test_idx]

    grid = GridSearchCV(
        KNeighborsClassifier(),
        knn_params,
        cv=inner_cv,
        scoring='roc_auc',
        n_jobs=-1
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_

    y_pred = best_model.predict(X_test)
    y_prob = best_model.predict_proba(X_test)[:, 1]

    knn_results.append({
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred),
        "recall": recall_score(y_test, y_pred),
        "f1": f1_score(y_test, y_pred),
        "roc_auc": roc_auc_score(y_test, y_prob)
    })

    print("Best Parameters:", grid.best_params_)

    fold += 1

import pandas as pd

knn_df = pd.DataFrame(knn_results)

print(knn_df.mean())

"""# 7. Support Vector Machine (SVM)

A subset of 20,000 samples is used due to computational limitations.
"""

svm_params = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf']
}

mlp_params = {
    'hidden_layer_sizes': [(50,), (100,)],
    'activation': ['relu', 'tanh']
}

xgb_params = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1]
}

svm_params = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf']
}
X_svm = X_selected.iloc[:20000]
y_svm = y.iloc[:20000]

print(X_svm.shape)
print(y_svm.shape)

"""# 8. Multi-Layer Perceptron (MLP)"""

from sklearn.svm import SVC

svm_results = []

fold = 1

for train_idx, test_idx in outer_cv.split(X_svm, y_svm):

    print(f"Processing Fold {fold}/5")

    X_train = X_svm.iloc[train_idx]
    X_test = X_svm.iloc[test_idx]

    y_train = y_svm.iloc[train_idx]
    y_test = y_svm.iloc[test_idx]

    grid = GridSearchCV(
        SVC(probability=True),
        svm_params,
        cv=inner_cv,
        scoring='roc_auc',
        n_jobs=-1
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_

    y_pred = best_model.predict(X_test)
    y_prob = best_model.predict_proba(X_test)[:, 1]

    svm_results.append({
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred),
        "recall": recall_score(y_test, y_pred),
        "f1": f1_score(y_test, y_pred),
        "roc_auc": roc_auc_score(y_test, y_prob)
    })

    print("Best Parameters:", grid.best_params_)

    fold += 1

svm_df = pd.DataFrame(svm_results)

print(svm_df.mean())

X_mlp = X_selected.iloc[:20000]
y_mlp = y.iloc[:20000]

print(X_mlp.shape)

mlp_params = {
    'hidden_layer_sizes': [(50,), (100,)],
    'activation': ['relu', 'tanh']
}

"""# 9. XGBoost Model"""

from sklearn.neural_network import MLPClassifier

mlp_results = []

fold = 1

for train_idx, test_idx in outer_cv.split(X_mlp, y_mlp):

    print(f"Processing Fold {fold}/5")

    X_train = X_mlp.iloc[train_idx]
    X_test = X_mlp.iloc[test_idx]

    y_train = y_mlp.iloc[train_idx]
    y_test = y_mlp.iloc[test_idx]

    grid = GridSearchCV(
        MLPClassifier(
            max_iter=200,
            random_state=42
        ),
        mlp_params,
        cv=inner_cv,
        scoring='roc_auc',
        n_jobs=-1
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_

    y_pred = best_model.predict(X_test)
    y_prob = best_model.predict_proba(X_test)[:, 1]

    mlp_results.append({
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred),
        "recall": recall_score(y_test, y_pred),
        "f1": f1_score(y_test, y_pred),
        "roc_auc": roc_auc_score(y_test, y_prob)
    })

    print("Best Parameters:", grid.best_params_)

    fold += 1

mlp_df = pd.DataFrame(mlp_results)

print(mlp_df.mean())

xgb_params = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1]
}

X_xgb = X_selected.iloc[:20000]
y_xgb = y.iloc[:20000]

print(X_xgb.shape)

xgb_params = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5],
    'learning_rate': [0.1]
}

"""# 10. Experimental Results"""

from xgboost import XGBClassifier

xgb_results = []

fold = 1

for train_idx, test_idx in outer_cv.split(X_xgb, y_xgb):

    print(f"Processing Fold {fold}/5")

    X_train = X_xgb.iloc[train_idx]
    X_test = X_xgb.iloc[test_idx]

    y_train = y_xgb.iloc[train_idx]
    y_test = y_xgb.iloc[test_idx]

    grid = GridSearchCV(
        XGBClassifier(
            random_state=42,
            eval_metric='logloss'
        ),
        xgb_params,
        cv=inner_cv,
        scoring='roc_auc',
        n_jobs=-1
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_

    y_pred = best_model.predict(X_test)
    y_prob = best_model.predict_proba(X_test)[:, 1]

    xgb_results.append({
        "accuracy": accuracy_score(y_test, y_pred),
        "precision": precision_score(y_test, y_pred),
        "recall": recall_score(y_test, y_pred),
        "f1": f1_score(y_test, y_pred),
        "roc_auc": roc_auc_score(y_test, y_prob)
    })

    print("Best Parameters:", grid.best_params_)

    fold += 1

xgb_df = pd.DataFrame(xgb_results)

print(xgb_df.mean())

results = pd.DataFrame({
    "Model": ["KNN", "SVM", "MLP", "XGBoost"],
    "Accuracy": [
        knn_df["accuracy"].mean(),
        svm_df["accuracy"].mean(),
        mlp_df["accuracy"].mean(),
        xgb_df["accuracy"].mean()
    ],
    "Precision": [
        knn_df["precision"].mean(),
        svm_df["precision"].mean(),
        mlp_df["precision"].mean(),
        xgb_df["precision"].mean()
    ],
    "Recall": [
        knn_df["recall"].mean(),
        svm_df["recall"].mean(),
        mlp_df["recall"].mean(),
        xgb_df["recall"].mean()
    ],
    "F1": [
        knn_df["f1"].mean(),
        svm_df["f1"].mean(),
        mlp_df["f1"].mean(),
        xgb_df["f1"].mean()
    ],
    "ROC_AUC": [
        knn_df["roc_auc"].mean(),
        svm_df["roc_auc"].mean(),
        mlp_df["roc_auc"].mean(),
        xgb_df["roc_auc"].mean()
    ]
})

results

best_model = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)

best_model.fit(X_xgb, y_xgb)

y_prob = best_model.predict_proba(X_xgb)[:, 1]

"""# 11. ROC Curve Analysis"""

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_xgb, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.4f}")
plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - XGBoost")
plt.legend()

plt.show()

feature_scores = pd.DataFrame({
    "Feature": X.columns,
    "Selected": selector.get_support()
})

feature_scores[feature_scores["Selected"]]